services:
  backend:
    build: ./restapi
    ports:
      - "8080:8080"
    volumes:
      - ./restapi:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
